/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storeproject.view;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import storeproject.helper.GenerateFile;
import storeproject.helper.RandomNumber;
import storeproject.list.Lists;
import storeproject.model.Bill;
import storeproject.model.CartTableModel;
import storeproject.model.CreditCard;
import storeproject.model.Product;

public class PaymentWindow extends javax.swing.JFrame {
    
    CartTableModel model = new CartTableModel();
    int option;
    RandomNumber random = RandomNumber.getSingletonInstance();
    String filename;
    Product tempProduct, cartProduct;
    CreditCard creditCard, userCreditCard;
    Bill currentBill;
    double oldGain, priceProduct;
    
    public PaymentWindow() {
        initComponents();
         setLocationRelativeTo(null);
        setResizable(false);
        productsTable.setModel(model);
        userNameTxt.setText( "Hola, " + LoginWindow.currentUser.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        CVCCodeTxt = new javax.swing.JTextField();
        tarjetNameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        billNameTxt = new javax.swing.JTextField();
        NitTxt = new javax.swing.JTextField();
        paymentBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        expirationDayCalendar = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CVC Code");

        jLabel2.setText("Fecha de vencimiento");

        jLabel3.setText("Nombre de la tarjeta");

        jLabel4.setText("Dirección de entrega");

        jLabel5.setText("Nombre de la factura");

        jLabel6.setText("Nit");

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(productsTable);

        CVCCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVCCodeTxtActionPerformed(evt);
            }
        });
        CVCCodeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CVCCodeTxtKeyTyped(evt);
            }
        });

        billNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNameTxtActionPerformed(evt);
            }
        });

        NitTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NitTxtKeyTyped(evt);
            }
        });

        paymentBtn.setText("Pagar");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Atrás");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CVCCodeTxt)
                            .addComponent(tarjetNameTxt)
                            .addComponent(addressTxt)
                            .addComponent(billNameTxt)
                            .addComponent(NitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(expirationDayCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CVCCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tarjetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(billNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(NitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(paymentBtn))
                    .addComponent(expirationDayCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNameTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        UserMainWindow userWindow = new UserMainWindow();
        userWindow.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed
    
    private boolean verifyCreditcard(CreditCard credicard){
        userCreditCard = LoginWindow.currentUser.getCreditCard();
        return userCreditCard.getCVCCode().equals(credicard.getCVCCode()) &&
                userCreditCard.getExpirationDate().equals(credicard.getExpirationDate()) &&
                userCreditCard.getCreditCardName().equals(credicard.getCreditCardName());
    }
    
    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        option = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea realizar la compra?");
        if(option == JOptionPane.YES_OPTION){
            creditCard = new CreditCard(tarjetNameTxt.getText(),getCurrentDate(expirationDayCalendar.getDate()),CVCCodeTxt.getText());
            if(verifyCreditcard(creditCard)){
                try{
                    Lists.bills.push(LoginWindow.currentUser, creditCard, addressTxt.getText(), billNameTxt.getText(), NitTxt.getText());
                    for(int i=1;i<LoginWindow.currentUser.getCart().getCartProducts().listSize();i++){
                        tempProduct = LoginWindow.currentUser.getCart().getCartProducts().getProductAt(i);
                        if(tempProduct!=null){
                            LoginWindow.currentUser.getPurchasedProducts().addToFinal(tempProduct.getIdentifier(), tempProduct.getName(), 
                                tempProduct.getDescription(), tempProduct.getPrice(), tempProduct.getStock(), tempProduct.getImageDirection(), 
                                tempProduct.getOffer());
                        }
                    }
                    for(int y=1;y<LoginWindow.currentUser.getCart().getCartProducts().listSize();y++){
                        oldGain = Lists.products.getProductByName(LoginWindow.currentUser.getCart().getCartProducts().getProductAt(y).getName()).getGain();
                        priceProduct = Lists.products.getProductByName(LoginWindow.currentUser.getCart().getCartProducts().getProductAt(y).getName()).getPrice();
                        Lists.products.getProductByName(LoginWindow.currentUser.getCart().getCartProducts().getProductAt(y).getName()).setGain(oldGain+priceProduct);
                    }
                    filename = "Factura"+random.generateIdentifier() ;
                    File f = new File(filename);
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.setSelectedFile(f);
                    int optionChoose = fileChooser.showSaveDialog(this);
                    if(optionChoose==JFileChooser.APPROVE_OPTION){
                        currentBill = new Bill(Lists.bills.listSize()-1,LoginWindow.currentUser, creditCard, addressTxt.getText(),
                                billNameTxt.getText(), NitTxt.getText() );
                        GenerateFile fileGenerator = new GenerateFile();
                        f = fileChooser.getSelectedFile();
                        fileGenerator.generateBill(f.toString(), currentBill);
                        JOptionPane.showMessageDialog(this, "Factura generada correctamente", "Generado",
                            JOptionPane.INFORMATION_MESSAGE);
                        CartWindow.cancelCart();
                        this.dispose();
                        UserMainWindow mainWindow = new UserMainWindow();
                        mainWindow.setVisible(true);
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Ocurrió un error, inténtelo de nuevo", "Error",
                                    JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Los datos de la tarjeta de credito no coinciden", "Error",
                                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_paymentBtnActionPerformed
    
    private String getCurrentDate(Date currentDate){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        return dateFormat.format(currentDate);
    }
    
    private void NitTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NitTxtKeyTyped
        char validChar = evt.getKeyChar();
        if(Character.isLetter(validChar)){
            getToolkit().beep();
            evt.consume();        
        }
    }//GEN-LAST:event_NitTxtKeyTyped

    private void CVCCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVCCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVCCodeTxtActionPerformed

    private void CVCCodeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CVCCodeTxtKeyTyped
        char validChar = evt.getKeyChar();
        if(Character.isLetter(validChar)){
            getToolkit().beep();
            evt.consume();        
        }
    }//GEN-LAST:event_CVCCodeTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVCCodeTxt;
    private javax.swing.JTextField NitTxt;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField billNameTxt;
    private com.toedter.calendar.JDateChooser expirationDayCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JTable productsTable;
    private javax.swing.JTextField tarjetNameTxt;
    private javax.swing.JLabel userNameTxt;
    // End of variables declaration//GEN-END:variables
}
