/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storeproject.view;

import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import storeproject.helper.GenerateFile;


public class ReportsWindow extends javax.swing.JFrame {

    GenerateFile fileGenerator = new GenerateFile();
    File currentFile;
    
    public ReportsWindow() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsPerUserBtn = new javax.swing.JButton();
        Top10Btn = new javax.swing.JButton();
        canceledPaymentsBtn = new javax.swing.JButton();
        productsWithOfferBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productsPerUserBtn.setText("Productos comprados por cada usuario");
        productsPerUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsPerUserBtnActionPerformed(evt);
            }
        });

        Top10Btn.setText("10 productos más vendidos ");
        Top10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Top10BtnActionPerformed(evt);
            }
        });

        canceledPaymentsBtn.setText("Usuarios que han cancelado sus compras");
        canceledPaymentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceledPaymentsBtnActionPerformed(evt);
            }
        });

        productsWithOfferBtn.setText("Productos con ofertas");
        productsWithOfferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsWithOfferBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Atrás");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsWithOfferBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(canceledPaymentsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(Top10Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productsPerUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(productsPerUserBtn)
                .addGap(18, 18, 18)
                .addComponent(Top10Btn)
                .addGap(18, 18, 18)
                .addComponent(canceledPaymentsBtn)
                .addGap(18, 18, 18)
                .addComponent(productsWithOfferBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canceledPaymentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceledPaymentsBtnActionPerformed
       try{
           currentFile = fileGenerator.generateCanceledPaymentReport("C:\\Users\\Omar\\Desktop\\StoreProject\\reports\\PagosCancelados");
           JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                            JOptionPane.INFORMATION_MESSAGE);
           Desktop.getDesktop().open(currentFile);
           currentFile.deleteOnExit();
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Ocurrió un error, inténtelo de nuevo", "Error",
                                JOptionPane.ERROR_MESSAGE);
       }   
    }//GEN-LAST:event_canceledPaymentsBtnActionPerformed

    private void productsPerUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsPerUserBtnActionPerformed
        try{
            currentFile = fileGenerator.generateProductsPerUserReport();
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                            JOptionPane.INFORMATION_MESSAGE);
            Desktop.getDesktop().open(currentFile);
            currentFile.deleteOnExit();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrió un error, inténtelo de nuevo", "Error",
                                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_productsPerUserBtnActionPerformed

    private void productsWithOfferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsWithOfferBtnActionPerformed
        try{
            currentFile = fileGenerator.generateProductsWithOffer();
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                            JOptionPane.INFORMATION_MESSAGE);
            Desktop.getDesktop().open(currentFile);
            currentFile.deleteOnExit();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrió un error, inténtelo de nuevo", "Error",
                                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_productsWithOfferBtnActionPerformed

    private void Top10BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Top10BtnActionPerformed
        try{
            fileGenerator.generateGraphic();
            JOptionPane.showMessageDialog(this, "Reporte generado correctamente", "Generado",
                            JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrió un error, inténtelo de nuevo", "Error",
                                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Top10BtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        AdministratorMainWindow main = new AdministratorMainWindow();
        main.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Top10Btn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton canceledPaymentsBtn;
    private javax.swing.JButton productsPerUserBtn;
    private javax.swing.JButton productsWithOfferBtn;
    // End of variables declaration//GEN-END:variables
}
